### ISSUE TITLE
The design for the web extension

### ISSUE THREAD

**Issue by SlShannon** [net-art-and-cultures/data-bodies#18]
<img width="422" alt="Web Extension" src="https://user-images.githubusercontent.com/54856596/68537139-2f45d380-0325-11ea-99ba-a7dc07577951.png">

**Comment by SlShannon** [comment]
<img width="803" alt="Screen Shot 2019-11-09 at 7 15 47 PM" src="https://user-images.githubusercontent.com/54856596/68537143-5c928180-0325-11ea-958f-cb7dd45969cd.png">

**Comment by nbriz** [comment]
these look super slick Shannon! don't forget to tag ur team (ie. @net-art-and-cultures/data-bodies ) so they get notified of this post && can comment on it. 

could u write a bit of a description for how the UX works? i assume "visit" takes u to the website && "save" saves it locally? or does it share it to the gallery? also what happens when u click the "+", is that how u start recording? what does it look like when the addon is currently recording? how do u stop the recording?

though the brush stroke in the back looks cool, i wonder if aesthetic details like this could be further tied into the theme of the piece. or, maybe it can reflect the aesthetic of the actual data portraits (which i know haven't been designed yet, but when they are it could help tie things together)

**Comment by SlShannon** [comment]
Thank you so much, sorry now I am adding everyone @jwham92 @harae37 @zylemma @Steve-luo @jlee273 @jwham92 

Yes, that's exactly right, the visit button can take the user into the Gallery website, then save button can save the screen capture of our recorded data on the social media websites, which then it will move into the smaller squares in the pop-up. ( maybe we can click on it and it will show the bigger image on image preview on the computer ) 

The additional "+" button can either take the screen capture or allows the user to add the additional images from the computer, such as uploading the image from users' computer gallery. I picked yellow, black, gray as the first concept design, ( it looks abstract because I assume the data can be more abstract looking) I am also open to additional color palette, but I would like to keep it only 4 different color palettes so the design won't get too busy,  ( maybe our color mark can have transparency, then we can use color's tint/shade to add more dimension to the design)

The Gallery website design is also very simple, I would like to include the hover on effects on the images ( once the mouse hovers on an image, it shows the date, time span of the data, which social media is used on the gallery image) , I also included "about" page on the website, in case we want to explain the purpose of creating this gallery.

**Comment by harae37** [comment]
@net-art-and-cultures/data-bodies 

Since we already have the link to the gallery on the preview boxes, how about we use one button to start generating and another to save the image? (So basically a start/end button)
And just have the three preview boxes show the saved ones but also have them linked to the gallery site, and no plus sign on the last one?

**Comment by harae37** [comment]
![popup](https://user-images.githubusercontent.com/47037744/69185580-a1b07380-0adc-11ea-9b26-9d0039b393d6.png)


button color: #6f79b8
